### ISSUE TITLE
coinbootmaker fails UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' 

### ISSUE THREAD

**Issue by frzb** [frzb/coinboot-plugins#3]
When calliing `coinbootmaker` with this plugin source:

```
create_plugin start

sudo echo 'deb http://cz.archive.ubuntu.com/ubuntu/ eoan universe'|sudo tee /etc/apt/sources.list.d/eoan_universe.list
sudo echo 'Package: * Pin: release n=eoan Pin-Priority: 50'|sudo tee /etc/apt/preferences.d/eoan
sudo apt update
sudo apt-get install --no-install-recommends --yes prometheus-node-exporter/eoan
sudo systemctl enable prometheus-node-exporter.service
sudo rm /etc/apt/preferences.d/eoan

create_plugin finish $0_$(date +%Y%m%d.%H%M)
```

```
 $ ./coinbootmaker -p coinboot-prometheus-node-exporter coinboot-initramfs-4.15.0-43-generic
```
It fails with:

```
[...]
Processing triggers for ureadahead (0.100.0-19) ...
Setting up libgdbm3:amd64 (1.8.3-13.1) ...
Setting up perl-modules-5.22 (5.22.1-9ubuntu0.6) ...
Setting up libperl5.22:amd64 (5.22.1-9ubuntu0.6) ...
Setting up perl (5.22.1-9ubuntu0.6) ...
update-alternatives: using /usr/bin/prename to provide /usr/bin/rename (rename) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/rename.1.gz because associated file /usr/share/man/man1/prename.1.gz (of link group rename) doesn't exist
Setting up libio-pty-perl (1:1.08-1.1build1) ...
Setting up libipc-run-perl (0.94-1) ...
Setting up libtime-duration-perl (1.21-1) ...
Setting up libtimedate-perl (2.3000-2) ...
Setting up moreutils (0.63-1) ...
Setting up prometheus-node-exporter (0.18.1+ds-1) ...
invoke-rc.d: could not determine current runlevel
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.15) ...
Processing triggers for ureadahead (0.100.0-19) ...
Synchronizing state of prometheus-node-exporter.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable prometheus-node-exporter
Traceback (most recent call last):
  File "/usr/local/bin/dpkg_status.py", line 79, in <module>
    main()
  File "/usr/local/bin/dpkg_status.py", line 73, in main
    print_dict(dict_diff)
  File "/usr/local/bin/dpkg_status.py", line 53, in print_dict
    print(set_dict[package_block] + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 449: ordinal not in range(128)
```

**Comment by frzb** [comment]
Issue is caused by the environment lacking support for UTF-8 locale:

```
root@coinbootmaker:/# locale -a
C
C.UTF-8
POSIX
en_US
en_US.iso88591
```
